blank_issues_enabled: false
contact_links:
  - name: Ask the community for help
    url: https://github.com/RashidKhanPathan/jekyll-theme-chirpy/discussions
    about: Please ask and answer questions here.
